In [2]:
import numpy as np

In [3]:
b = np.array([i for i in range(10)])
print(b)
print(type(b))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
# можем создавать массив из кортежа
c = (1,2,3,4,5,6,7)
b = np.array(c)
print(b)

[1 2 3 4 5 6 7]


In [9]:
# можем создвать массив только с определенным типом данных
a = [1,2,3,4,5,6,7,8]
b = np.array(a, dtype = float)
print(b)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [12]:
a = [1,2,3,4,5,6,7,8,9.9]
b = np.array(a, dtype = int)
print(b)
print(b.dtype)
b = np.array(a, dtype = str)
print(b)
print(b.dtype)

[1 2 3 4 5 6 7 8 9]
int32
['1' '2' '3' '4' '5' '6' '7' '8' '9.9']
<U3


In [14]:
# Размерность массива
print(b.ndim)
# Количество элементов
print(b.shape)

1
(9,)


In [22]:
# двумерный массив:
b = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 0, 1, 2], [13, 35, 64, 75, 43, 12]])
print(b)
print(b.ndim)
print(b.shape)
# общее количество элементов
print(b.size)

[[ 1  2  3  4  5  6]
 [ 7  8  9  0  1  2]
 [13 35 64 75 43 12]]
2
(3, 6)
18


In [29]:
# доступ к элементам строка - столбец
print(b[1][0])
print(b[1, 1])

7
8


In [28]:
# можно делать срез [от строки:по строку][от столбца:по столбец]
b[0:2, 0:3]

array([[1, 2, 3],
       [7, 8, 9]])

In [30]:
b[1:, 3:]

array([[ 0,  1,  2],
       [75, 43, 12]])

In [38]:
c = b[1:, 3:]
print(c)

[[ 0  1  2]
 [75 43 12]]


In [40]:
# если мы поменяем в матрице c элемент то он так же изменится и в b
c[0, 1] = 999
print(c)
print(b)

[[  0 999   2]
 [ 75  43  12]]
[[  1   2   3   4   5   6]
 [  7   8   9   0 999   2]
 [ 13  35  64  75  43  12]]


In [41]:
# если мы хотим чтобы с был отдельным элементом то необходимо применить copy
c = b[1:, 3:].copy()
c[0, 0] = 777
print(c)
print(b)

[[777 999   2]
 [ 75  43  12]]
[[  1   2   3   4   5   6]
 [  7   8   9   0 999   2]
 [ 13  35  64  75  43  12]]


In [43]:
# типы данных 
b = np.array([1.,2.,3.], dtype=np.float32)
print(b.dtype)
b = np.array([1.,2.,3.], dtype=np.float64)
print(b.dtype)
b = np.array([1.,2.,3.], dtype=np.int32)
print(b.dtype)
b = np.array([1.,2.,3.], dtype=np.int64)
print(b.dtype)

float32
float64
int32
int64


In [44]:
# применение библиотеки numpy для линейной алгебры
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# сложение
c = a + b
print(c)

[ 6  8 10 12 14]


In [45]:
# для сравнения списки в python
x1 = [1,2,3,4,5]
x2 = [5,6,7,8,9]
print(x1 + x2)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [47]:
# чтобы не запутаться функция add
c = np.add(a, b)
print(c)

[ 6  8 10 12 14]


In [139]:
# если количестов элементов разное то результаты + и add  - ошибка
a1 = np.array([1,2,3,4,5,8])
b1 = np.array([5,6,7,8,9])


In [50]:
d = a - b
print(d)
print(np.subtract(a, b))

[-4 -4 -4 -4 -4]
[-4 -4 -4 -4 -4]


In [55]:
# умножение
print(a * 2)
print(np.dot(-10, a))
print(a.dot(-10))
print(np.multiply(-10, a))

[ 2  4  6  8 10]
[-10 -20 -30 -40 -50]
[-10 -20 -30 -40 -50]
[-10 -20 -30 -40 -50]


In [53]:
# умножение в спискох приводит к другим результатам - дублирование
print(2 * [1,2,3])

[1, 2, 3, 1, 2, 3]


In [56]:
# скалярное произведение
sp = a @ b
print(sp)
print(np.dot(a, b))

115
115


In [59]:
# операции с матрицами
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9], [10, 11]])

# сложение
C = A + B
print(C)
print(np.add(A, B))

[[ 6  8]
 [10 12]
 [14 16]]
[[ 6  8]
 [10 12]
 [14 16]]


In [61]:
# вычитание
print(A - B)
print(np.subtract(A, B))

[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [63]:
# умножение на скаляр
Y = A * 3
print(Y)
print(np.dot(A, 3))

[[ 0  3]
 [ 6  9]
 [12 15]]
[[ 0  3]
 [ 6  9]
 [12 15]]


In [68]:
# умножение матриц друг на друга
X1 = np.array([[1,2], [2,3], [4,5]])
X2 = np.array([[1,2,3,4], [4,5,6,7]])
X1.shape[1] == X2.shape[0]

True

In [70]:
Z = np.dot(X1, X2)
print(Z)

[[ 9 12 15 18]
 [14 19 24 29]
 [24 33 42 51]]


In [76]:
# возведение матрицы в квадрат - матрица должна быть квадратной
A_s = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(np.dot(A_s,A_s))
print(np.linalg.matrix_power(A_s, 2))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [80]:
# создание единичной матрицы
I = np.eye(2)
A = np.array([[0, 1], [2, 3], [4, 5]])
print(I)
print(np.dot(A, I))
I = np.eye(3)
print(np.dot(I, A))

[[1. 0.]
 [0. 1.]]
[[0. 1.]
 [2. 3.]
 [4. 5.]]
[[0. 1.]
 [2. 3.]
 [4. 5.]]


In [82]:
# транспонирование матрицы
A = np.array([[0, 1], [2, 3], [4, 5]])
At = A.transpose()
print(At)

At = A.T
print(At)

[[0 2 4]
 [1 3 5]]
[[0 2 4]
 [1 3 5]]


In [83]:
X = np.array([[1,2],[3,4],[5,6]])
Y = np.array([[0,1],[2,1],[3,4],[5,6]])
Yt = Y.T
print(Yt)

[[0 2 3 5]
 [1 1 4 6]]


In [84]:
print(np.dot(X, Yt))

[[ 2  4 11 17]
 [ 4 10 25 39]
 [ 6 16 39 61]]


In [88]:
# определитель матрицы
A_s = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(np.linalg.det(A_s))
# ранг матрицы
print(np.linalg.matrix_rank(A_s))

0.0
2


In [90]:
# обратная матрица
A_s = np.array([[0,1,2], [3,7,5], [6,47,8]])
A_inv = np.linalg.inv(A_s)
print(A_inv)

[[-0.87745098  0.42156863 -0.04411765]
 [ 0.02941176 -0.05882353  0.02941176]
 [ 0.48529412  0.02941176 -0.01470588]]


In [91]:
A_inv_inv = np.linalg.inv(A_inv)
print(A_inv_inv)

[[-0.  1.  2.]
 [ 3.  7.  5.]
 [ 6. 47.  8.]]


In [92]:
# Автоматическое создание массивов
# нулей
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [93]:
a = np.ones((5, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [96]:
# массив с последовательностью
print(np.arange(10))
print(np.arange(4, 10))
print(np.arange(4, 40, 5))

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 4  9 14 19 24 29 34 39]


In [98]:
# в arange - правая граница не включается, а в linspace включена
print(np.linspace(0, 9.9, 100))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [101]:
# в качестве левой и правой границы мы указываем степени числа 10
print(np.logspace(0, 3, 5))

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [102]:
# генерация рандомных чисел в промежуткке от 0.0 до 0.1
print(np.random.sample())

0.7856263264325338


In [103]:
# если указываем аргумент - то получим количество рандомных чисел
print(np.random.sample(4))

[0.25074723 0.44998443 0.38895102 0.40032037]


In [105]:
print(np.random.sample((2,4)))

[[0.36060598 0.89032472 0.7238171  0.87456063]
 [0.07995746 0.35500307 0.49039798 0.90834573]]


In [112]:
# нормальное распределение среднее значение - 0, среднеквадратичное откланение - 1
print(np.random.randn(10)) #  аргумент - количество чисел
print(np.random.randn(3, 4)) # массив

[ 0.41581592  1.88678594  0.0084464  -0.83234586 -2.14586773 -0.45507722
 -0.5610883   1.09222168 -0.05961667  0.99728536]
[[ 0.83258429  1.03047758 -0.22542826  1.05555139]
 [-0.27161011  1.49097355  0.80324087  0.22852555]
 [-2.3237688  -0.94123453  0.22305405 -0.98837188]]


In [111]:
# массив целых чисел
print(np.random.randint(0, 199, 10)) # 10 чисел в заданном промежутке
print(np.random.randint(0, 199, (3, 4))) # массив в заданном промежутке

[ 70 105  91 137  38 184 128  95  14  47]
[[  4  75  21  39]
 [108 191  23 195]
 [168 197  62 169]]


In [115]:
# случайный выбор из элементов массива
b = np.array([1,2,3,4,5,6,7,8])
print(np.random.choice(b))
print(np.random.choice(b, 2)) # аргумент - количество чисел


1
[3 2]


In [117]:
# random - псевдо случайное число numpy.random.seed - инициализация генератора случайных чисел
np.random.seed(42)
print(np.random.randint(0,10,3))

[6 3 7]


In [127]:
# изменение формы массива
a = np.arange(12)
b = np.arange(12)
print(a)
print(a.reshape(3, 4))
print(b.reshape(3, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [133]:
# изменение формы на месте
a = np.arange(12)
a.resize(2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [134]:
# из многомерного массива одномерный массив
a = a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [136]:
# соединение массивов вертикально
a = np.zeros((2, 3))
b = np.ones((2, 3))
v = np.vstack((a, b))
print(v)

print(np.concatenate((a, b), axis = 0))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [137]:
# соединение массивов горизонтально
h = np.hstack((a, b))
print(h)
print(np.concatenate((a,b), axis = 1))

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [138]:
# соединение в глубину
print(np.dstack([a, b]))

[[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]


In [140]:
# выбор данных из массива
a = np.random.randint(0, 20, 10)
print(a)

[ 6 18 10 10  3  7  2  1 11  5]


In [141]:
print(a[a > 10])

[18 11]


In [144]:
print(a[(a > 10) & (a % 2 == 0)])

[18]


In [145]:
print(a[(a > 10) | (a % 2 == 0)])

[ 6 18 10 10  2 11]


In [147]:
# выборка - where - возвращает индексы соответствующих условию элементов
print(a)
print(np.where(a > 10))

[ 6 18 10 10  3  7  2  1 11  5]
(array([1, 8], dtype=int64),)


In [148]:
a[np.where(a > 10)]

array([18, 11])

In [149]:
# Если в условии true то берем из а если false то из b
a = [1, 4, 7]
b = [9, 2, 5]
np.where([True, False, True], a, b)

array([1, 2, 7])

In [150]:
# сортировка
a = np.array([[1, 3, 9, 9], [5, 0, 1, 5], [2, 7, 3, 5]])
# отсортируем по 2 столбцу
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [151]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [152]:
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [153]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [154]:
# случайное перемешивание
a = np.arange(10)
np.random.shuffle(a)
print(a)

[5 2 7 6 8 9 3 0 4 1]


In [158]:
# перемешиваются только строки

am = np.arange(12).reshape(4, 3)
np.random.shuffle(am)
print(am)

[[ 0  1  2]
 [ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]]


In [159]:
# Математические действия ко всему массиву
a = np.arange(1, 7).reshape(2, 3)
# вычисляем логарифм по отношению к каждому элементу
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [160]:
# вычислим экспоненту
print(np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [161]:
# сумма по каждому столбцу
a.sum(axis = 0)

array([5, 7, 9])

In [162]:
a.sum(axis = 1)

array([ 6, 15])

In [167]:
# поэлементное умножение 
a = np.arange(12).reshape(3, -1)
print(a)
b = np.arange(12, 24).reshape(-1, 4)
print(b)
print(a * b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [170]:
# Broadcasting (когда размерности не совпадают)
a = np.array([[2, 5], [3, 4], [6, 1]])
b = np.array([1, 2])
print(a + b)

c = np.array([[1], [2], [3]])
print(a + c)

[[3 7]
 [4 6]
 [7 3]]
[[3 6]
 [5 6]
 [9 4]]


In [171]:
# Стастистические функции
a = np.random.randint(0, 12, (3, 4))
print(a)

[[ 2 11  6  3]
 [ 8  2  4  2]
 [ 6  4  8  6]]


In [175]:
# минимальное значение
print(a.min())
print(a.min(axis = 0))

2
[2 2 4 2]


In [176]:
# среднее значение
print(a.mean())
print(a.mean(axis = 0))

5.166666666666667
[5.33333333 5.66666667 6.         3.66666667]


In [177]:
# среднеквадратичное отклонение
print(a.std())
print(a.std(axis = 0))

2.733536577809454
[2.49443826 3.8586123  1.63299316 1.69967317]


In [178]:
# прочитатть массив из файла
# сохранение
np.save('a.npy', a)
# загрузка
np.load('a.npy')


array([[ 2, 11,  6,  3],
       [ 8,  2,  4,  2],
       [ 6,  4,  8,  6]])