In [3]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно.

In [4]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [13]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [15]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(4, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [23]:
a5.ndim
# Нет, так как только массив строка является одномерным массивом

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [29]:
b = np.random.randn(3, 4)
print(b)
b1 = b.flatten()
print(b1)

[[-0.75270735  0.77941716 -1.03583042 -2.526887  ]
 [-0.11069637  0.91730367  1.31545596  0.81987693]
 [-0.89570065 -0.15039366  0.76848905 -0.40372119]]
[-0.75270735  0.77941716 -1.03583042 -2.526887   -0.11069637  0.91730367
  1.31545596  0.81987693 -0.89570065 -0.15039366  0.76848905 -0.40372119]


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [30]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [33]:
b = np.arange(20, 1, -2).reshape(1, 10)
print(b)
# b - двумерный массив, a - одномерный

[[20 18 16 14 12 10  8  6  4  2]]


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [39]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
ab_vertical = np.vstack((a, b))
print(ab_vertical)
print(ab_vertical.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At 
с помощью матричного умножения. 
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [154]:
a = np.arange(0, 12)
print(a)
A = a.reshape(4, 3)
print(A)
At = A.T
B = A.dot(At)
print(B)
B.size
# Матирца имеет размер 4х4
d = np.linalg.det(B)
print(d)
# обратную матрицу вычислить не удастся т.к. определитель матрицы равен 0

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
0.0


10.  Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [4]:
np.random.seed(42)
print(np.random.randint(5))

3


11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных
целых чисел от 0 до 16 невключительно. 

In [151]:
c = np.random.randint(0,16,16)
print(c)

[ 0  7  2  2  0 10  4  9  6  9  8 11  6  8  7 11]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [161]:
C = c.reshape(4, 4)
print(C)
D = np.add(C, (B.dot(10)))
print(D)
det = np.linalg.det(D)
print(det)
rank = np.linalg.matrix_rank(D)
print(rank)
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0  7  2  2]
 [ 0 10  4  9]
 [ 6  9  8 11]
 [ 6  8  7 11]]
[[  50  147  232  322]
 [ 140  510  864 1229]
 [ 236  869 1498 2131]
 [ 326 1228 2127 3031]]
-136042.00000001834
4
[[-0.4977654   0.19106599  1.05241764 -0.7645139 ]
 [ 0.21314006  0.03338675 -0.52005998  0.32945708]
 [ 0.84866438 -0.57785096 -1.25386278  1.02569795]
 [-0.62836477  0.37142941  0.97740404 -0.77070317]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where,
используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv
равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему
элементу матрицы C.

In [172]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
print(D_inv)

if D_inv[(D_inv != 0) & (D_inv != 1)].size == 0:
    print('Все элементы либоб 0 либо 1')
    
E = np.where(D_inv, B, C)
print(E)

[[0. 1. 1. 0.]
 [1. 1. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]
Все элементы либоб 0 либо 1
[[  0  14  23   2]
 [ 14  50   4 122]
 [ 23   9   8 212]
 [  6 122 212  11]]
